### ISSUE TITLE
Basic install documentation

### ISSUE THREAD

**Issue by markbrough** [devgateway/iatiimport#1]
It would be great to have some basic installation documentation on here. Particularly:
* how to get the Java back-end up and running
* how to get only the Grunt front-end up and running

Is it necessary to have the Java back-end running for the UI (or even just a mock-up) working?

**Comment by markbrough** [comment]
Are there any other dependencies required by the existing source code (e.g. expectation that there is a DG AMP to write to)?

**Comment by markbrough** [comment]
OK so you can get the prototype running with:
```
cd import-core/import-ui/src/main/webapp/prototype
python -m SimpleHTTPServer
```
There also appears to be something in `import-core/import-ui/src/main/resources/static`

To get the main app running I think you have to do something like:
```
cd import-core/import-ui/src/main/webapp
npm install --dev
grunt serve
```
However, it looks like the Java back-end is needed to get this running properly?

**Comment by gmutuhu** [comment]
1. I have added information on how to run the tool in the  README.md. 
2. While it is possible to run the front-end only using 'grunt serve', the Tool requires the backend to be running since the processing of the IATI files is done on the backend.
3. The IATI Import tool expects the availability of a target system that implements the endpoints described in the 'Destination System REST Endpoint Requirements' section in the wiki. This does not have to be AMP.

**Comment by markbrough** [comment]
Great, thanks! Is there a way to see a demo of the tool without having the back-end running? Or do you have a live instance somewhere to play with? Screenshots might even do.

**Comment by joshuacpowell** [comment]
Hi Mark,
There is a demo instance - will email you with log-in details.
